// <auto-generated />
using System;
using BaiTapLon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTapLon.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    [Migration("20260917150108_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BaiTapLon.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Cà phê pha phin truyền thống Việt Nam đậm đà bản sắc",
                            DisplayOrder = 1,
                            Icon = "fa-coffee",
                            Name = "Cà Phê Truyền Thống"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Espresso, Cappuccino, Latte phong cách Ý thượng hạng",
                            DisplayOrder = 2,
                            Icon = "fa-mug-hot",
                            Name = "Cà Phê Pha Máy (Espresso)"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Trà đào cam sả, trà vải, trà sen thanh mát ngọt dịu",
                            DisplayOrder = 3,
                            Icon = "fa-leaf",
                            Name = "Trà & Trà Trái Cây"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Matcha, Socola, Sinh tố xoài béo ngậy thơm ngon",
                            DisplayOrder = 4,
                            Icon = "fa-glass-water",
                            Name = "Đá Xay & Sinh Tố (Ice Blended)"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Tiramisu, Croissant, Bánh phô mai nướng thơm lừng",
                            DisplayOrder = 5,
                            Icon = "fa-cookie-bite",
                            Name = "Bánh Ngọt & Tráng Miệng"
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.CoffeeTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TableId"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TableId");

                    b.ToTable("CoffeeTables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Area = "Tầng 1",
                            Capacity = 2,
                            Status = "Available",
                            TableName = "Bàn 01"
                        },
                        new
                        {
                            TableId = 2,
                            Area = "Tầng 1",
                            Capacity = 4,
                            Status = "Available",
                            TableName = "Bàn 02"
                        },
                        new
                        {
                            TableId = 3,
                            Area = "Tầng 1",
                            Capacity = 4,
                            Status = "Occupied",
                            TableName = "Bàn 03"
                        },
                        new
                        {
                            TableId = 4,
                            Area = "Tầng 1",
                            Capacity = 6,
                            Status = "Available",
                            TableName = "Bàn 04"
                        },
                        new
                        {
                            TableId = 5,
                            Area = "Tầng 2",
                            Capacity = 2,
                            Status = "Available",
                            TableName = "Bàn 05"
                        },
                        new
                        {
                            TableId = 6,
                            Area = "Tầng 2",
                            Capacity = 4,
                            Status = "Reserved",
                            TableName = "Bàn 06"
                        },
                        new
                        {
                            TableId = 7,
                            Area = "Tầng 2",
                            Capacity = 6,
                            Status = "Available",
                            TableName = "Bàn 07"
                        },
                        new
                        {
                            TableId = 8,
                            Area = "Sân Vườn",
                            Capacity = 4,
                            Status = "Available",
                            TableName = "Bàn Sân Vườn 01"
                        },
                        new
                        {
                            TableId = 9,
                            Area = "Sân Vườn",
                            Capacity = 8,
                            Status = "Available",
                            TableName = "Bàn Sân Vườn 02"
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BaiTapLon.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BaiTapLon.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Robusta nguyên chất Đắk Lắk pha phin truyền thống, vị đắng thanh đậm đà.",
                            ImageUrl = "/images/products/ca-phe-den.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Cà Phê Đen Đá",
                            Price = 25000m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Cà phê đậm đà hòa quyện cùng sữa đặc béo ngậy, thức uống quốc dân.",
                            ImageUrl = "/images/products/ca-phe-sua.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Cà Phê Sữa Đá",
                            Price = 29000m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Nhiều sữa đặc và sữa tươi kèm một chút cà phê thơm dịu dàng.",
                            ImageUrl = "/images/products/bac-xiu.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Bạc Xỉu Sài Gòn",
                            Price = 32000m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Chiết xuất áp suất cao từ hạt Arabica Cầu Đất nguyên chất.",
                            ImageUrl = "/images/products/espresso.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Espresso Đậm Vị",
                            Price = 35000m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Espresso kết hợp sữa nóng và lớp bọt sữa dày mịn rắc bột cacao.",
                            ImageUrl = "/images/products/cappuccino.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Cappuccino Ý",
                            Price = 45000m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Sốt caramel béo ngọt quyện cùng vị đắng nhẹ của cà phê pha máy.",
                            ImageUrl = "/images/products/macchiato.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Caramel Macchiato",
                            Price = 49000m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Trà đen hương đào thanh mát, sả tươi ngát hương cùng miếng đào giòn ngọt.",
                            ImageUrl = "/images/products/tra-dao.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Trà Đào Cam Sả",
                            Price = 39000m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "Trà lài thơm nức kết hợp quả vải ngâm ngọt mọng nước.",
                            ImageUrl = "/images/products/tra-vai.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Trà Vải Hoa Nhài",
                            Price = 39000m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Description = "Bột trà xanh Nhật Bản xay nhuyễn với đá viên và lớp kem tươi whipping cream.",
                            ImageUrl = "/images/products/matcha-ice.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Matcha Đá Xay Kem Béo",
                            Price = 49000m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            Description = "Hương vị sô cô la đậm đà the mát cùng tinh chất bạc hà sảng khoái.",
                            ImageUrl = "/images/products/choco-mint.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Socola Bạc Hà Đá Xay",
                            Price = 49000m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 5,
                            Description = "Bánh kem phô mai mascarpone đượm vị cà phê rượu nhẹ rắc bột cacao.",
                            ImageUrl = "/images/products/tiramisu.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Bánh Tiramisu Ý",
                            Price = 38000m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 5,
                            Description = "Bánh sừng bò nướng giòn rụm với nhiều lớp bơ thơm ngát.",
                            ImageUrl = "/images/products/croissant.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Bánh Croissant Bơ Pháp",
                            Price = 32000m
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@cafe.vn",
                            FullName = "Quản Trị Viên",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            PhoneNumber = "0901234567",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@cafe.vn",
                            FullName = "Nhân Viên Thu Ngân",
                            PasswordHash = "EBdue3sk0xes/PjSBkz9LyThVPe1qWYDB31e+BPWprY=",
                            PhoneNumber = "0908888999",
                            Role = "Staff",
                            Username = "staff"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khach@gmail.com",
                            FullName = "Nguyễn Văn Khách",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            PhoneNumber = "0912345678",
                            Role = "Customer",
                            Username = "khachhang"
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Order", b =>
                {
                    b.HasOne("BaiTapLon.Models.CoffeeTable", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId");

                    b.HasOne("BaiTapLon.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaiTapLon.Models.OrderDetail", b =>
                {
                    b.HasOne("BaiTapLon.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapLon.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BaiTapLon.Models.Product", b =>
                {
                    b.HasOne("BaiTapLon.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BaiTapLon.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BaiTapLon.Models.CoffeeTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BaiTapLon.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BaiTapLon.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BaiTapLon.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
