// <auto-generated />
using System;
using BaiTapLon.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BaiTapLon.Migrations
{
    [DbContext(typeof(CoffeeShopDbContext))]
    partial class CoffeeShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BaiTapLon.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Cà phê pha phin truyền thống Việt Nam đậm đà bản sắc",
                            DisplayOrder = 1,
                            Icon = "fa-coffee",
                            Name = "Cà Phê Truyền Thống"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Espresso, Cappuccino, Latte phong cách Ý thượng hạng",
                            DisplayOrder = 2,
                            Icon = "fa-mug-hot",
                            Name = "Cà Phê Pha Máy (Espresso)"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Trà đào cam sả, trà vải, trà sen thanh mát ngọt dịu",
                            DisplayOrder = 3,
                            Icon = "fa-leaf",
                            Name = "Trà & Trà Trái Cây"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Matcha, Socola, Sinh tố xoài béo ngậy thơm ngon",
                            DisplayOrder = 4,
                            Icon = "fa-glass-water",
                            Name = "Đá Xay & Sinh Tố (Ice Blended)"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Tiramisu, Croissant, Bánh phô mai nướng thơm lừng",
                            DisplayOrder = 5,
                            Icon = "fa-cookie-bite",
                            Name = "Bánh Ngọt & Tráng Miệng"
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.CoffeeTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TableId"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("TableId");

                    b.ToTable("CoffeeTables");

                    b.HasData(
                        new
                        {
                            TableId = 1,
                            Area = "Tầng 1",
                            Capacity = 2,
                            Status = "Available",
                            TableName = "Bàn 01"
                        },
                        new
                        {
                            TableId = 2,
                            Area = "Tầng 1",
                            Capacity = 4,
                            Status = "Available",
                            TableName = "Bàn 02"
                        },
                        new
                        {
                            TableId = 3,
                            Area = "Tầng 1",
                            Capacity = 4,
                            Status = "Occupied",
                            TableName = "Bàn 03"
                        },
                        new
                        {
                            TableId = 4,
                            Area = "Tầng 1",
                            Capacity = 6,
                            Status = "Available",
                            TableName = "Bàn 04"
                        },
                        new
                        {
                            TableId = 5,
                            Area = "Tầng 2",
                            Capacity = 2,
                            Status = "Available",
                            TableName = "Bàn 05"
                        },
                        new
                        {
                            TableId = 6,
                            Area = "Tầng 2",
                            Capacity = 4,
                            Status = "Reserved",
                            TableName = "Bàn 06"
                        },
                        new
                        {
                            TableId = 7,
                            Area = "Tầng 2",
                            Capacity = 6,
                            Status = "Available",
                            TableName = "Bàn 07"
                        },
                        new
                        {
                            TableId = 8,
                            Area = "Sân Vườn",
                            Capacity = 4,
                            Status = "Available",
                            TableName = "Bàn Sân Vườn 01"
                        },
                        new
                        {
                            TableId = 9,
                            Area = "Sân Vườn",
                            Capacity = 8,
                            Status = "Available",
                            TableName = "Bàn Sân Vườn 02"
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.EmployeeSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WorkDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("ScheduleId");

                    b.HasIndex("ShiftId");

                    b.HasIndex("UserId");

                    b.ToTable("EmployeeSchedules");

                    b.HasData(
                        new
                        {
                            ScheduleId = 1,
                            Note = "Trực quầy thu ngân và kiểm tra quầy bánh",
                            ShiftId = 1,
                            Status = "Completed",
                            UserId = 2,
                            WorkDate = new DateTime(2026, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 2,
                            Note = "Phụ trách pha chế máy Espresso",
                            ShiftId = 2,
                            Status = "Scheduled",
                            UserId = 2,
                            WorkDate = new DateTime(2026, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ScheduleId = 3,
                            Note = "Trực bàn và kiểm kê kho cuối ca",
                            ShiftId = 3,
                            Status = "Scheduled",
                            UserId = 2,
                            WorkDate = new DateTime(2026, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<decimal>("MinimumStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("QuantityInStock")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SupplierId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IngredientId");

                    b.HasIndex("SupplierId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            MinimumStock = 10m,
                            Name = "Hạt Cà Phê Arabica Cầu Đất",
                            QuantityInStock = 50m,
                            SupplierId = 1,
                            Unit = "kg",
                            UnitPrice = 280000m
                        },
                        new
                        {
                            IngredientId = 2,
                            MinimumStock = 15m,
                            Name = "Hạt Cà Phê Robusta Buôn Ma Thuột",
                            QuantityInStock = 80m,
                            SupplierId = 1,
                            Unit = "kg",
                            UnitPrice = 160000m
                        },
                        new
                        {
                            IngredientId = 3,
                            MinimumStock = 20m,
                            Name = "Sữa Đặc Có Đường Ông Thọ",
                            QuantityInStock = 120m,
                            SupplierId = 2,
                            Unit = "hộp",
                            UnitPrice = 24000m
                        },
                        new
                        {
                            IngredientId = 4,
                            MinimumStock = 15m,
                            Name = "Sữa Tươi Thanh Trùng 100%",
                            QuantityInStock = 60m,
                            SupplierId = 2,
                            Unit = "lít",
                            UnitPrice = 35000m
                        },
                        new
                        {
                            IngredientId = 5,
                            MinimumStock = 5m,
                            Name = "Trà Đen Hương Đào Cao Cấp",
                            QuantityInStock = 25m,
                            SupplierId = 3,
                            Unit = "kg",
                            UnitPrice = 220000m
                        },
                        new
                        {
                            IngredientId = 6,
                            MinimumStock = 10m,
                            Name = "Đào Miếng Ngâm Nước Đường",
                            QuantityInStock = 45m,
                            SupplierId = 3,
                            Unit = "hộp",
                            UnitPrice = 42000m
                        },
                        new
                        {
                            IngredientId = 7,
                            MinimumStock = 3m,
                            Name = "Bột Trà Xanh Matcha Uji Nhật Bản",
                            QuantityInStock = 15m,
                            SupplierId = 3,
                            Unit = "kg",
                            UnitPrice = 650000m
                        },
                        new
                        {
                            IngredientId = 8,
                            MinimumStock = 5m,
                            Name = "Sốt Caramel Torani Nhập Khẩu",
                            QuantityInStock = 20m,
                            SupplierId = 3,
                            Unit = "chai",
                            UnitPrice = 185000m
                        },
                        new
                        {
                            IngredientId = 9,
                            MinimumStock = 5m,
                            Name = "Bột Cacao Nguyên Chất",
                            QuantityInStock = 18m,
                            SupplierId = 3,
                            Unit = "kg",
                            UnitPrice = 210000m
                        },
                        new
                        {
                            IngredientId = 10,
                            MinimumStock = 300m,
                            Name = "Cốc Giấy Take-away & Nắp Sinh Học",
                            QuantityInStock = 2000m,
                            SupplierId = 4,
                            Unit = "cái",
                            UnitPrice = 1500m
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<int?>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("ViewCount")
                        .HasColumnType("int");

                    b.HasKey("NewsId");

                    b.HasIndex("AuthorId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            NewsId = 1,
                            AuthorId = 1,
                            Content = "<p>Cà phê phin từ lâu đã trở thành biểu tượng của sự tĩnh lặng và kiên nhẫn. Những giọt Robusta sánh đậm hòa cùng sữa đặc béo ngọt tạo nên bản hòa ca vị giác khó quên...</p>",
                            ImageUrl = "/images/products/ca-phe-den.jpg",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "nghe-thuat-thuong-thuc-ca-phe-pha-phin",
                            Summary = "Từng giọt cà phê nhỏ chậm rãi qua chiếc phin nhôm không chỉ là cách chiết xuất hương vị, mà là cả một nét văn hóa sống chậm thanh tao của người Việt.",
                            Title = "Nghệ Thuật Thưởng Thức Cà Phê Pha Phin Truyền Thống Việt Nam",
                            ViewCount = 385
                        },
                        new
                        {
                            NewsId = 2,
                            AuthorId = 1,
                            Content = "<p>Những trái cà phê chín đỏ được người nông dân hái thủ công, sơ chế ướt và rang mộc ở mức vừa phải để lưu giữ trọn vẹn hương hoa cỏ thanh nhã...</p>",
                            ImageUrl = "/images/products/espresso.jpg",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "hanh-trinh-hat-arabica-cau-dat",
                            Summary = "Nằm ở độ cao trên 1500m so với mực nước biển, Cầu Đất (Đà Lạt) được thiên nhiên ưu ái khí hậu ôn đới lý tưởng để ươm mầm những hạt Arabica thơm ngọt dịu dàng.",
                            Title = "Hành Trình Hạt Arabica Từ Vùng Đất Cầu Đất Đến Tách Cà Phê Của Bạn",
                            ViewCount = 290
                        },
                        new
                        {
                            NewsId = 3,
                            AuthorId = 1,
                            Content = "<p>Với mong muốn mang lại nguồn cảm hứng bất tận khi làm việc và trò chuyện, khu vực sân vườn được trang bị hệ thống phun sương mát mẻ và ổ cắm điện tiện lợi...</p>",
                            ImageUrl = "/images/products/tra-dao.jpg",
                            IsActive = true,
                            PublishedAt = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Slug = "khai-truong-khong-gian-rooftop-san-vuon",
                            Summary = "Coffee Paradise chính thức ra mắt khu vực sân vườn ngoài trời ngập tràn cây xanh và góc rooftop ngắm hoàng hôn cực chill dành cho các bạn trẻ.",
                            Title = "Khai Trương Không Gian Rooftop & Sân Vườn Xanh Mát",
                            ViewCount = 512
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("CustomerPhone")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<int?>("TableId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("TableId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BaiTapLon.Models.OrderDetail", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("OrderDetailId"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("BaiTapLon.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Description = "Robusta nguyên chất Đắk Lắk pha phin truyền thống, vị đắng thanh đậm đà.",
                            ImageUrl = "/images/products/ca-phe-den.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Cà Phê Đen Đá",
                            Price = 25000m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            Description = "Cà phê đậm đà hòa quyện cùng sữa đặc béo ngậy, thức uống quốc dân.",
                            ImageUrl = "/images/products/ca-phe-sua.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Cà Phê Sữa Đá",
                            Price = 29000m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            Description = "Nhiều sữa đặc và sữa tươi kèm một chút cà phê thơm dịu dàng.",
                            ImageUrl = "/images/products/bac-xiu.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Bạc Xỉu Sài Gòn",
                            Price = 32000m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 2,
                            Description = "Chiết xuất áp suất cao từ hạt Arabica Cầu Đất nguyên chất.",
                            ImageUrl = "/images/products/espresso.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Espresso Đậm Vị",
                            Price = 35000m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Description = "Espresso kết hợp sữa nóng và lớp bọt sữa dày mịn rắc bột cacao.",
                            ImageUrl = "/images/products/cappuccino.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Cappuccino Ý",
                            Price = 45000m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Description = "Sốt caramel béo ngọt quyện cùng vị đắng nhẹ của cà phê pha máy.",
                            ImageUrl = "/images/products/macchiato.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Caramel Macchiato",
                            Price = 49000m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 3,
                            Description = "Trà đen hương đào thanh mát, sả tươi ngát hương cùng miếng đào giòn ngọt.",
                            ImageUrl = "/images/products/tra-dao.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Trà Đào Cam Sả",
                            Price = 39000m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 3,
                            Description = "Trà lài thơm nức kết hợp quả vải ngâm ngọt mọng nước.",
                            ImageUrl = "/images/products/tra-vai.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Trà Vải Hoa Nhài",
                            Price = 39000m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 4,
                            Description = "Bột trà xanh Nhật Bản xay nhuyễn với đá viên và lớp kem tươi whipping cream.",
                            ImageUrl = "/images/products/matcha-ice.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Matcha Đá Xay Kem Béo",
                            Price = 49000m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 4,
                            Description = "Hương vị sô cô la đậm đà the mát cùng tinh chất bạc hà sảng khoái.",
                            ImageUrl = "/images/products/choco-mint.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Socola Bạc Hà Đá Xay",
                            Price = 49000m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 5,
                            Description = "Bánh kem phô mai mascarpone đượm vị cà phê rượu nhẹ rắc bột cacao.",
                            ImageUrl = "/images/products/tiramisu.jpg",
                            IsAvailable = true,
                            IsFeatured = true,
                            Name = "Bánh Tiramisu Ý",
                            Price = 38000m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 5,
                            Description = "Bánh sừng bò nướng giòn rụm với nhiều lớp bơ thơm ngát.",
                            ImageUrl = "/images/products/croissant.jpg",
                            IsAvailable = true,
                            IsFeatured = false,
                            Name = "Bánh Croissant Bơ Pháp",
                            Price = 32000m
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<decimal>("AmountNeeded")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("RecipeId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("ProductId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            AmountNeeded = 25m,
                            IngredientId = 2,
                            ProductId = 1,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = 2,
                            AmountNeeded = 25m,
                            IngredientId = 2,
                            ProductId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = 3,
                            AmountNeeded = 30m,
                            IngredientId = 3,
                            ProductId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = 4,
                            AmountNeeded = 18m,
                            IngredientId = 1,
                            ProductId = 4,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = 5,
                            AmountNeeded = 18m,
                            IngredientId = 1,
                            ProductId = 5,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = 6,
                            AmountNeeded = 150m,
                            IngredientId = 4,
                            ProductId = 5,
                            Unit = "ml"
                        },
                        new
                        {
                            RecipeId = 7,
                            AmountNeeded = 15m,
                            IngredientId = 5,
                            ProductId = 7,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = 8,
                            AmountNeeded = 50m,
                            IngredientId = 6,
                            ProductId = 7,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = 9,
                            AmountNeeded = 10m,
                            IngredientId = 7,
                            ProductId = 9,
                            Unit = "g"
                        },
                        new
                        {
                            RecipeId = 10,
                            AmountNeeded = 100m,
                            IngredientId = 4,
                            ProductId = 9,
                            Unit = "ml"
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ReviewId = 1,
                            Comment = "Cà phê sữa đá rất đậm đà, chuẩn vị Tây Nguyên, không bị ngọt gắt. Rất hài lòng!",
                            CreatedAt = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Nguyễn Văn Khách",
                            IsApproved = true,
                            ProductId = 2,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 2,
                            Comment = "Trà đào cam sả thơm lừng vị sả tươi, miếng đào giòn ngọt và thanh mát.",
                            CreatedAt = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Trần Hoàng Anh",
                            IsApproved = true,
                            ProductId = 7,
                            Rating = 5,
                            UserId = 3
                        },
                        new
                        {
                            ReviewId = 3,
                            Comment = "Cappuccino bọt sữa vẽ hình rất đẹp, ấm nóng và béo mịn. Sẽ quay lại thử thêm món khác!",
                            CreatedAt = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Lê Thu Thảo",
                            IsApproved = true,
                            ProductId = 5,
                            Rating = 4
                        },
                        new
                        {
                            ReviewId = 4,
                            Comment = "Matcha đá xay thơm chuẩn matcha Nhật, kem whipping cream béo ngậy ăn cực mê!",
                            CreatedAt = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Phạm Minh Đức",
                            IsApproved = true,
                            ProductId = 9,
                            Rating = 5
                        },
                        new
                        {
                            ReviewId = 5,
                            Comment = "Bánh Tiramisu mềm mịn, đậm đà vị cà phê rượu và không bị ngấy xíu nào.",
                            CreatedAt = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CustomerName = "Vũ Mai Linh",
                            IsApproved = true,
                            ProductId = 11,
                            Rating = 5
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Shift", b =>
                {
                    b.Property<int>("ShiftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ShiftId"));

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time(6)");

                    b.Property<decimal>("HourlyWage")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShiftName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time(6)");

                    b.HasKey("ShiftId");

                    b.ToTable("Shifts");

                    b.HasData(
                        new
                        {
                            ShiftId = 1,
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            HourlyWage = 26000m,
                            ShiftName = "Ca Sáng (Mở Cửa & Chuẩn Bị)",
                            StartTime = new TimeSpan(0, 7, 0, 0, 0)
                        },
                        new
                        {
                            ShiftId = 2,
                            EndTime = new TimeSpan(0, 17, 30, 0, 0),
                            HourlyWage = 26000m,
                            ShiftName = "Ca Chiều (Phục Vụ Cao Điểm)",
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            ShiftId = 3,
                            EndTime = new TimeSpan(0, 22, 30, 0, 0),
                            HourlyWage = 29000m,
                            ShiftName = "Ca Tối (Chill & Dọn Dẹp)",
                            StartTime = new TimeSpan(0, 17, 30, 0, 0)
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            SupplierId = 1,
                            Address = "Xã Xuân Trường, TP. Đà Lạt, Lâm Đồng",
                            ContactPerson = "Nguyễn Hữu Đạt",
                            Email = "dat@caudatfarm.vn",
                            Name = "Nông Trại Cà Phê Cầu Đất Farm",
                            PhoneNumber = "0987111222"
                        },
                        new
                        {
                            SupplierId = 2,
                            Address = "Khu công nghiệp Lộc Phát, Lâm Đồng",
                            ContactPerson = "Trần Thị Mai",
                            Email = "mai.tt@vinamilk.com.vn",
                            Name = "Công Ty Sữa Vinamilk Chi Nhánh Đà Lạt",
                            PhoneNumber = "0988222333"
                        },
                        new
                        {
                            SupplierId = 3,
                            Address = "Quận Tân Phú, TP. Hồ Chí Minh",
                            ContactPerson = "Lê Quang Minh",
                            Email = "minh@tannhathuong.com",
                            Name = "Công Ty Nguyên Liệu Pha Chế Tân Nhất Hương",
                            PhoneNumber = "0909333444"
                        },
                        new
                        {
                            SupplierId = 4,
                            Address = "Gia Lâm, Hà Nội",
                            ContactPerson = "Phạm Gia Huy",
                            Email = "contact@ecocup.vn",
                            Name = "Công Ty Bao Bì & Cốc Giấy Thân Thiện Eco Cup",
                            PhoneNumber = "0918444555"
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@cafe.vn",
                            FullName = "Quản Trị Viên",
                            PasswordHash = "JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=",
                            PhoneNumber = "0901234567",
                            Role = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "staff@cafe.vn",
                            FullName = "Nhân Viên Thu Ngân",
                            PasswordHash = "EBdue3sk0xes/PjSBkz9LyThVPe1qWYDB31e+BPWprY=",
                            PhoneNumber = "0908888999",
                            Role = "Staff",
                            Username = "staff"
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "khach@gmail.com",
                            FullName = "Nguyễn Văn Khách",
                            PasswordHash = "jZae727K08KaOmKSgOaGzww/XVqGr/PKEgIMkjrcbJI=",
                            PhoneNumber = "0912345678",
                            Role = "Customer",
                            Username = "khachhang"
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Voucher", b =>
                {
                    b.Property<int>("VoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VoucherId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DiscountPercent")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UsageLimit")
                        .HasColumnType("int");

                    b.Property<int>("UsedCount")
                        .HasColumnType("int");

                    b.HasKey("VoucherId");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Vouchers");

                    b.HasData(
                        new
                        {
                            VoucherId = 1,
                            Code = "CHAOBAN",
                            DiscountPercent = 10,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaxDiscountAmount = 30000m,
                            MinOrderAmount = 50000m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 500,
                            UsedCount = 42
                        },
                        new
                        {
                            VoucherId = 2,
                            Code = "COFFEE20",
                            DiscountPercent = 20,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaxDiscountAmount = 50000m,
                            MinOrderAmount = 80000m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 200,
                            UsedCount = 88
                        },
                        new
                        {
                            VoucherId = 3,
                            Code = "FREESHIP",
                            DiscountPercent = 15,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaxDiscountAmount = 25000m,
                            MinOrderAmount = 60000m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 1000,
                            UsedCount = 156
                        },
                        new
                        {
                            VoucherId = 4,
                            Code = "VIPSTUDENT",
                            DiscountPercent = 15,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            MaxDiscountAmount = 40000m,
                            MinOrderAmount = 40000m,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UsageLimit = 300,
                            UsedCount = 65
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.Wishlist", b =>
                {
                    b.Property<int>("WishlistId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("WishlistId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WishlistId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Wishlists");

                    b.HasData(
                        new
                        {
                            WishlistId = 1,
                            CreatedAt = new DateTime(2026, 9, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 2,
                            UserId = 3
                        },
                        new
                        {
                            WishlistId = 2,
                            CreatedAt = new DateTime(2026, 9, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 7,
                            UserId = 3
                        },
                        new
                        {
                            WishlistId = 3,
                            CreatedAt = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProductId = 5,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("BaiTapLon.Models.EmployeeSchedule", b =>
                {
                    b.HasOne("BaiTapLon.Models.Shift", "Shift")
                        .WithMany("EmployeeSchedules")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapLon.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaiTapLon.Models.Ingredient", b =>
                {
                    b.HasOne("BaiTapLon.Models.Supplier", "Supplier")
                        .WithMany("Ingredients")
                        .HasForeignKey("SupplierId");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("BaiTapLon.Models.News", b =>
                {
                    b.HasOne("BaiTapLon.Models.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BaiTapLon.Models.Order", b =>
                {
                    b.HasOne("BaiTapLon.Models.CoffeeTable", "Table")
                        .WithMany("Orders")
                        .HasForeignKey("TableId");

                    b.HasOne("BaiTapLon.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Table");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaiTapLon.Models.OrderDetail", b =>
                {
                    b.HasOne("BaiTapLon.Models.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapLon.Models.Product", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BaiTapLon.Models.Product", b =>
                {
                    b.HasOne("BaiTapLon.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BaiTapLon.Models.Recipe", b =>
                {
                    b.HasOne("BaiTapLon.Models.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapLon.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BaiTapLon.Models.Review", b =>
                {
                    b.HasOne("BaiTapLon.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapLon.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaiTapLon.Models.Wishlist", b =>
                {
                    b.HasOne("BaiTapLon.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BaiTapLon.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BaiTapLon.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BaiTapLon.Models.CoffeeTable", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BaiTapLon.Models.Ingredient", b =>
                {
                    b.Navigation("Recipes");
                });

            modelBuilder.Entity("BaiTapLon.Models.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BaiTapLon.Models.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BaiTapLon.Models.Shift", b =>
                {
                    b.Navigation("EmployeeSchedules");
                });

            modelBuilder.Entity("BaiTapLon.Models.Supplier", b =>
                {
                    b.Navigation("Ingredients");
                });

            modelBuilder.Entity("BaiTapLon.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
